services:
  pop_pul:
    image: mysql:8.0
    container_name: pop_pul-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:  # 볼륨을 명시적으로 정의

